window.SmartBI_TokensData = [
  { name: "--sbi-brand-name", value: "\"Smart BI\"" },
  { name: "--sbi-brand-tagline", value: "\"Conversational BI\"" },
  { name: "--sbi-brand-personality", value: "\"playful-precision\"" },
  { name: "--sbi-color-navy-950", value: "215 55% 12%" },
  { name: "--sbi-color-navy-900", value: "215 50% 18%" },
  { name: "--sbi-color-navy-800", value: "215 48% 23%" },
  { name: "--sbi-color-navy-700", value: "215 45% 28%" },
  { name: "--sbi-color-navy-600", value: "215 42% 33%" },
  { name: "--sbi-color-navy-500", value: "215 38% 42%" },
  { name: "--sbi-color-navy-400", value: "215 30% 55%" },
  { name: "--sbi-color-navy-300", value: "215 22% 70%" },
  { name: "--sbi-color-navy-200", value: "215 18% 85%" },
  { name: "--sbi-color-navy-100", value: "215 15% 93%" },
  { name: "--sbi-color-navy-50", value: "210 20% 98%" },
  { name: "--sbi-color-orange-900", value: "25 90% 30%" },
  { name: "--sbi-color-orange-800", value: "28 88% 38%" },
  { name: "--sbi-color-orange-700", value: "30 85% 44%" },
  { name: "--sbi-color-orange-600", value: "32 82% 50%" },
  { name: "--sbi-color-orange-500", value: "35 80% 55%" },
  { name: "--sbi-color-orange-400", value: "38 85% 62%" },
  { name: "--sbi-color-orange-300", value: "40 88% 72%" },
  { name: "--sbi-color-orange-200", value: "42 90% 84%" },
  { name: "--sbi-color-orange-100", value: "44 92% 92%" },
  { name: "--sbi-color-orange-50", value: "45 95% 96%" },
  { name: "--sbi-color-blue-900", value: "222 70% 28%" },
  { name: "--sbi-color-blue-800", value: "222 75% 38%" },
  { name: "--sbi-color-blue-700", value: "222 80% 48%" },
  { name: "--sbi-color-blue-600", value: "222 85% 58%" },
  { name: "--sbi-color-blue-500", value: "222 98% 66%" },
  { name: "--sbi-color-blue-400", value: "222 95% 72%" },
  { name: "--sbi-color-blue-300", value: "222 90% 82%" },
  { name: "--sbi-color-blue-200", value: "222 85% 90%" },
  { name: "--sbi-color-blue-100", value: "222 80% 95%" },
  { name: "--sbi-color-blue-50", value: "222 75% 97%" },
  { name: "--sbi-color-teal-700", value: "174 55% 30%" },
  { name: "--sbi-color-teal-600", value: "174 58% 38%" },
  { name: "--sbi-color-teal-500", value: "174 60% 45%" },
  { name: "--sbi-color-teal-400", value: "174 55% 55%" },
  { name: "--sbi-color-teal-300", value: "174 50% 68%" },
  { name: "--sbi-color-teal-200", value: "174 45% 82%" },
  { name: "--sbi-color-teal-100", value: "174 40% 92%" },
  { name: "--sbi-color-teal-50", value: "174 35% 96%" },
  { name: "--sbi-color-purple-600", value: "250 55% 52%" },
  { name: "--sbi-color-purple-500", value: "250 60% 60%" },
  { name: "--sbi-color-purple-400", value: "250 65% 68%" },
  { name: "--sbi-color-purple-300", value: "250 70% 78%" },
  { name: "--sbi-color-purple-100", value: "250 75% 94%" },
  { name: "--sbi-color-green-900", value: "152 60% 18%" },
  { name: "--sbi-color-green-800", value: "152 58% 24%" },
  { name: "--sbi-color-green-700", value: "152 55% 32%" },
  { name: "--sbi-color-green-600", value: "152 55% 38%" },
  { name: "--sbi-color-green-500", value: "152 55% 45%" },
  { name: "--sbi-color-green-400", value: "148 50% 50%" },
  { name: "--sbi-color-green-300", value: "145 45% 62%" },
  { name: "--sbi-color-green-200", value: "142 40% 80%" },
  { name: "--sbi-color-green-100", value: "140 35% 92%" },
  { name: "--sbi-color-green-50", value: "138 30% 96%" },
  { name: "--sbi-color-green-brand", value: "152 78% 28%" },
  { name: "--sbi-color-charcoal-900", value: "0 5% 12%" },
  { name: "--sbi-color-charcoal-800", value: "0 3% 18%" },
  { name: "--sbi-color-charcoal-700", value: "0 2% 24%" },
  { name: "--sbi-color-charcoal-600", value: "200 3% 36%" },
  { name: "--sbi-color-charcoal-500", value: "200 2% 44%" },
  { name: "--sbi-color-charcoal-400", value: "200 2% 54%" },
  { name: "--sbi-color-charcoal-300", value: "200 2% 72%" },
  { name: "--sbi-color-charcoal-200", value: "200 3% 86%" },
  { name: "--sbi-color-charcoal-100", value: "30 8% 94%" },
  { name: "--sbi-color-charcoal-50", value: "30 6% 97%" },
  { name: "--sbi-color-warm-100", value: "40 33% 97%" },
  { name: "--sbi-color-warm-200", value: "210 33% 95%" },
  { name: "--sbi-color-warm-300", value: "210 20% 93%" },
  { name: "--sbi-color-warm-400", value: "214 15% 91%" },
  { name: "--sbi-color-slate-950", value: "222 47% 7%" },
  { name: "--sbi-color-slate-900", value: "222 47% 11%" },
  { name: "--sbi-color-slate-800", value: "215 28% 17%" },
  { name: "--sbi-color-slate-700", value: "215 25% 27%" },
  { name: "--sbi-color-slate-600", value: "215 20% 35%" },
  { name: "--sbi-color-slate-500", value: "215 16% 47%" },
  { name: "--sbi-color-slate-400", value: "215 14% 57%" },
  { name: "--sbi-color-slate-300", value: "214 20% 75%" },
  { name: "--sbi-color-slate-200", value: "214 25% 88%" },
  { name: "--sbi-color-slate-100", value: "210 25% 96%" },
  { name: "--sbi-color-slate-50", value: "210 25% 98%" },
  { name: "--sbi-color-red-600", value: "0 72% 51%" },
  { name: "--sbi-color-red-500", value: "0 84% 60%" },
  { name: "--sbi-color-red-100", value: "0 93% 94%" },
  { name: "--sbi-color-amber-500", value: "38 92% 50%" },
  { name: "--sbi-color-cyan-400", value: "199 89% 58%" },
  { name: "--sbi-color-yellow-500", value: "45 93% 47%" },
  { name: "--sbi-color-white", value: "0 0% 100%" },
  { name: "--sbi-color-black", value: "0 0% 0%" },
  { name: "--sbi-color-transparent", value: "transparent" },
  { name: "--sbi-chart-series-1", value: "222 98% 66%" },
  { name: "--sbi-chart-series-2", value: "35 80% 55%" },
  { name: "--sbi-chart-series-3", value: "174 60% 45%" },
  { name: "--sbi-chart-series-4", value: "152 55% 45%" },
  { name: "--sbi-chart-series-5", value: "0 72% 51%" },
  { name: "--sbi-chart-series-6", value: "250 60% 60%" },
  { name: "--sbi-chart-series-7", value: "45 93% 47%" },
  { name: "--sbi-chart-series-8", value: "199 89% 48%" },
  { name: "--sbi-alpha-navy-04", value: "215 42% 33% / 0.04" },
  { name: "--sbi-alpha-navy-06", value: "215 42% 33% / 0.06" },
  { name: "--sbi-alpha-navy-08", value: "215 42% 33% / 0.08" },
  { name: "--sbi-alpha-navy-10", value: "215 42% 33% / 0.10" },
  { name: "--sbi-alpha-navy-12", value: "215 42% 33% / 0.12" },
  { name: "--sbi-alpha-navy-15", value: "215 42% 33% / 0.15" },
  { name: "--sbi-alpha-blue-10", value: "222 98% 66% / 0.10" },
  { name: "--sbi-alpha-blue-20", value: "222 98% 66% / 0.20" },
  { name: "--sbi-alpha-blue-40", value: "222 98% 66% / 0.40" },
  { name: "--sbi-alpha-orange-15", value: "35 80% 55% / 0.15" },
  { name: "--sbi-alpha-orange-30", value: "35 80% 55% / 0.30" },
  { name: "--sbi-alpha-white-80", value: "0 0% 100% / 0.80" },
  { name: "--sbi-alpha-white-90", value: "0 0% 100% / 0.90" },
  { name: "--sbi-alpha-black-03", value: "0 0% 0% / 0.03" },
  { name: "--sbi-alpha-black-05", value: "0 0% 0% / 0.05" },
  { name: "--sbi-alpha-black-08", value: "0 0% 0% / 0.08" },
  { name: "--sbi-alpha-black-12", value: "0 0% 0% / 0.12" },
  { name: "--sbi-font-family-sans", value: "'Inter', system-ui, -apple-system, 'Segoe UI', sans-serif" },
  { name: "--sbi-font-family-display", value: "'Space Grotesk', var(--sbi-font-family-sans)" },
  { name: "--sbi-font-family-mono", value: "'Consolas', 'Monaco', 'Andale Mono', 'Ubuntu Mono', monospace" },
  { name: "--sbi-font-size-2xs", value: "0.5625rem" },
  { name: "--sbi-font-size-xs", value: "0.6875rem" },
  { name: "--sbi-font-size-sm", value: "0.8125rem" },
  { name: "--sbi-font-size-md", value: "0.875rem" },
  { name: "--sbi-font-size-base", value: "0.9375rem" },
  { name: "--sbi-font-size-lg", value: "1rem" },
  { name: "--sbi-font-size-xl", value: "1.625rem" },
  { name: "--sbi-font-size-2xl", value: "1.75rem" },
  { name: "--sbi-font-size-3xl", value: "2rem" },
  { name: "--sbi-font-size-4xl", value: "2.375rem" },
  { name: "--sbi-font-size-5xl", value: "clamp(1.5rem, 5vw, 2.375rem)" },
  { name: "--sbi-font-size-hero", value: "clamp(1.5rem, 6vw, 2.375rem)" },
  { name: "--sbi-font-weight-regular", value: "400" },
  { name: "--sbi-font-weight-medium", value: "500" },
  { name: "--sbi-font-weight-semibold", value: "600" },
  { name: "--sbi-font-weight-bold", value: "700" },
  { name: "--sbi-line-height-tight", value: "1.25" },
  { name: "--sbi-line-height-snug", value: "1.3" },
  { name: "--sbi-line-height-normal", value: "1.4" },
  { name: "--sbi-line-height-relaxed", value: "1.5" },
  { name: "--sbi-line-height-loose", value: "1.6" },
  { name: "--sbi-letter-spacing-tighter", value: "-0.02em" },
  { name: "--sbi-letter-spacing-tight", value: "-0.01em" },
  { name: "--sbi-letter-spacing-normal", value: "0" },
  { name: "--sbi-letter-spacing-wide", value: "0.05em" },
  { name: "--sbi-letter-spacing-wider", value: "0.10em" },
  { name: "--sbi-letter-spacing-widest", value: "0.12em" },
  { name: "--sbi-text-eyebrow-size", value: "var(--sbi-font-size-xs)" },
  { name: "--sbi-text-eyebrow-weight", value: "var(--sbi-font-weight-semibold)" },
  { name: "--sbi-text-eyebrow-spacing", value: "var(--sbi-letter-spacing-widest)" },
  { name: "--sbi-text-eyebrow-transform", value: "uppercase" },
  { name: "--sbi-text-display-size", value: "var(--sbi-font-size-4xl)" },
  { name: "--sbi-text-display-weight", value: "var(--sbi-font-weight-regular)" },
  { name: "--sbi-text-display-height", value: "var(--sbi-line-height-snug)" },
  { name: "--sbi-text-display-spacing", value: "var(--sbi-letter-spacing-tighter)" },
  { name: "--sbi-text-heading-size", value: "var(--sbi-font-size-3xl)" },
  { name: "--sbi-text-heading-weight", value: "var(--sbi-font-weight-regular)" },
  { name: "--sbi-text-heading-height", value: "var(--sbi-line-height-snug)" },
  { name: "--sbi-text-body-size", value: "var(--sbi-font-size-base)" },
  { name: "--sbi-text-body-weight", value: "var(--sbi-font-weight-regular)" },
  { name: "--sbi-text-body-height", value: "var(--sbi-line-height-loose)" },
  { name: "--sbi-text-caption-size", value: "var(--sbi-font-size-sm)" },
  { name: "--sbi-text-caption-weight", value: "var(--sbi-font-weight-regular)" },
  { name: "--sbi-text-caption-height", value: "var(--sbi-line-height-relaxed)" },
  { name: "--sbi-text-label-size", value: "var(--sbi-font-size-xs)" },
  { name: "--sbi-text-label-weight", value: "var(--sbi-font-weight-semibold)" },
  { name: "--sbi-text-label-spacing", value: "var(--sbi-letter-spacing-wider)" },
  { name: "--sbi-text-label-transform", value: "uppercase" },
  { name: "--sbi-space-0", value: "0" },
  { name: "--sbi-space-px", value: "1px" },
  { name: "--sbi-space-0-5", value: "0.125rem" },
  { name: "--sbi-space-1", value: "0.25rem" },
  { name: "--sbi-space-1-5", value: "0.375rem" },
  { name: "--sbi-space-2", value: "0.5rem" },
  { name: "--sbi-space-2-5", value: "0.625rem" },
  { name: "--sbi-space-3", value: "0.75rem" },
  { name: "--sbi-space-3-5", value: "0.875rem" },
  { name: "--sbi-space-4", value: "1rem" },
  { name: "--sbi-space-5", value: "1.25rem" },
  { name: "--sbi-space-6", value: "1.5rem" },
  { name: "--sbi-space-7", value: "1.75rem" },
  { name: "--sbi-space-8", value: "2rem" },
  { name: "--sbi-space-9", value: "2.25rem" },
  { name: "--sbi-space-10", value: "2.5rem" },
  { name: "--sbi-space-12", value: "3rem" },
  { name: "--sbi-space-14", value: "3.5rem" },
  { name: "--sbi-space-15", value: "3.75rem" },
  { name: "--sbi-space-16", value: "4rem" },
  { name: "--sbi-space-18", value: "4.5rem" },
  { name: "--sbi-space-20", value: "5rem" },
  { name: "--sbi-space-24", value: "6rem" },
  { name: "--sbi-layout-section-gap", value: "var(--gap-section)" },
  { name: "--sbi-layout-component-gap", value: "var(--gap-component)" },
  { name: "--sbi-layout-element-gap", value: "var(--gap-element)" },
  { name: "--sbi-layout-micro-gap", value: "var(--gap-micro)" },
  { name: "--sbi-layout-container-max", value: "1280px" },
  { name: "--sbi-layout-content-max", value: "1080px" },
  { name: "--sbi-layout-goal-max", value: "1200px" },
  { name: "--sbi-layout-side-padding", value: "var(--side-padding-fluid)" },
  { name: "--sbi-layout-nav-height", value: "60px" },
  { name: "--sbi-radius-none", value: "0" },
  { name: "--sbi-radius-xs", value: "0.1875rem" },
  { name: "--sbi-radius-sm", value: "0.25rem" },
  { name: "--sbi-radius-md", value: "0.375rem" },
  { name: "--sbi-radius-lg", value: "0.5rem" },
  { name: "--sbi-radius-xl", value: "0.75rem" },
  { name: "--sbi-radius-2xl", value: "1rem" },
  { name: "--sbi-radius-3xl", value: "1.5rem" },
  { name: "--sbi-radius-full", value: "9999px" },
  { name: "--sbi-border-width-hairline", value: "1px" },
  { name: "--sbi-border-width-medium", value: "2px" },
  { name: "--sbi-border-width-thick", value: "3px" },
  { name: "--sbi-shadow-xs", value: "0 1px 2px 0 hsl(var(--sbi-alpha-navy-04))" },
  { name: "--sbi-shadow-sm", value: "0 1px 2px 0 hsl(var(--sbi-alpha-navy-04))" },
  { name: "--sbi-shadow-md", value: "0 4px 6px -1px hsl(var(--sbi-alpha-navy-08)), 0 2px 4px -2px hsl(var(--sbi-alpha-navy-04))" },
  { name: "--sbi-shadow-lg", value: "0 10px 15px -3px hsl(var(--sbi-alpha-navy-10)), 0 4px 6px -4px hsl(var(--sbi-alpha-navy-04))" },
  { name: "--sbi-shadow-xl", value: "0 20px 25px -5px hsl(var(--sbi-alpha-navy-10)), 0 8px 10px -6px hsl(var(--sbi-alpha-navy-04))" },
  { name: "--sbi-shadow-2xl", value: "0 20px 40px hsl(var(--sbi-alpha-navy-06))" },
  { name: "--sbi-shadow-card", value: "0 4px 24px -4px hsl(var(--sbi-alpha-navy-12))" },
  { name: "--sbi-shadow-card-hover", value: "0 12px 38px hsl(var(--sbi-alpha-navy-08)), 0 6px 16px hsl(var(--sbi-alpha-blue-10))" },
  { name: "--sbi-shadow-goal-dark", value: "0 10px 30px hsl(var(--sbi-alpha-black-04))" },
  { name: "--sbi-shadow-ai-card", value: "0 20px 40px hsl(var(--sbi-alpha-black-06))" },
  { name: "--sbi-shadow-mockup", value: "0 20px 45px hsl(var(--sbi-alpha-black-08))" },
  { name: "--sbi-shadow-glow-blue", value: "0 0 0 3px hsl(var(--sbi-alpha-blue-10))" },
  { name: "--sbi-shadow-glow-orange", value: "0 0 40px hsl(var(--sbi-alpha-orange-30))" },
  { name: "--sbi-shadow-glow-error", value: "0 0 12px hsl(0 72% 51% / 0.15)" },
  { name: "--sbi-shadow-emoji", value: "0 12px 24px hsl(var(--sbi-alpha-black-08)), 0 4px 8px hsl(var(--sbi-alpha-black-04))" },
  { name: "--sbi-shadow-nav", value: "0 8px 24px hsl(var(--sbi-alpha-black-08)), 0 1px 3px hsl(var(--sbi-alpha-black-04))" },
  { name: "--sbi-gradient-hero-navy", value: "linear-gradient( 135deg, hsl(var(--sbi-color-navy-600)) 0%, hsl(var(--sbi-color-navy-900)) 100% )" },
  { name: "--sbi-gradient-accent-orange", value: "linear-gradient( 135deg, hsl(var(--sbi-color-orange-500)) 0%, hsl(25 90% 50%) 100% )" },
  { name: "--sbi-gradient-teal", value: "linear-gradient( 135deg, hsl(var(--sbi-color-teal-500)) 0%, hsl(180 50% 35%) 100% )" },
  { name: "--sbi-gradient-purple", value: "linear-gradient( 135deg, hsl(var(--sbi-color-purple-500)) 0%, hsl(260 50% 50%) 100% )" },
  { name: "--sbi-gradient-card", value: "linear-gradient( 180deg, hsl(var(--sbi-color-white)) 0%, hsl(var(--sbi-color-navy-50)) 100% )" },
  { name: "--sbi-gradient-mesh-playful", value: "radial-gradient( at 40% 20%, hsl(var(--sbi-alpha-orange-15)) 0px, transparent 50% ), radial-gradient( at 80% 0%, hsl(174 60% 45% / 0.10) 0px, transparent 50% ), radial-gradient( at 0% 50%, hsl(250 60% 60% / 0.08) 0px, transparent 50% )" },
  { name: "--sbi-gradient-goal-section", value: "linear-gradient( 180deg, hsl(var(--sbi-color-warm-200)) 0%, hsl(210 30% 93%) 100% )" },
  { name: "--sbi-gradient-dark-card", value: "linear-gradient( 145deg, hsl(var(--sbi-color-charcoal-900)) 0%, hsl(var(--sbi-color-navy-900)) 100% )" },
  { name: "--sbi-duration-instant", value: "0ms" },
  { name: "--sbi-duration-fastest", value: "100ms" },
  { name: "--sbi-duration-fast", value: "150ms" },
  { name: "--sbi-duration-normal", value: "200ms" },
  { name: "--sbi-duration-moderate", value: "300ms" },
  { name: "--sbi-duration-slow", value: "400ms" },
  { name: "--sbi-duration-slower", value: "600ms" },
  { name: "--sbi-duration-slowest", value: "800ms" },
  { name: "--sbi-duration-chart", value: "1000ms" },
  { name: "--sbi-duration-typewriter-char", value: "70ms" },
  { name: "--sbi-duration-ai-think", value: "1200ms" },
  { name: "--sbi-duration-scenario-hold", value: "6000ms" },
  { name: "--sbi-ease-linear", value: "linear" },
  { name: "--sbi-ease-in", value: "cubic-bezier(0.4, 0, 1, 1)" },
  { name: "--sbi-ease-out", value: "cubic-bezier(0, 0, 0.2, 1)" },
  { name: "--sbi-ease-in-out", value: "cubic-bezier(0.4, 0, 0.2, 1)" },
  { name: "--sbi-ease-smooth", value: "cubic-bezier(0.25, 0.8, 0.25, 1)" },
  { name: "--sbi-ease-spring-soft", value: "cubic-bezier(0.22, 1, 0.36, 1)" },
  { name: "--sbi-ease-spring-bounce", value: "cubic-bezier(0.175, 0.885, 0.32, 1.275)" },
  { name: "--sbi-ease-chart-draw", value: "cubic-bezier(0.16, 1, 0.3, 1)" },
  { name: "--sbi-ease-nav-underline", value: "cubic-bezier(0.4, 0, 0.2, 1)" },
  { name: "--sbi-transition-color", value: "color var(--sbi-duration-normal) var(--sbi-ease-out), background-color var(--sbi-duration-normal) var(--sbi-ease-out), border-color var(--sbi-duration-normal) var(--sbi-ease-out)" },
  { name: "--sbi-transition-transform", value: "transform var(--sbi-duration-normal) var(--sbi-ease-spring-bounce)" },
  { name: "--sbi-transition-shadow", value: "box-shadow var(--sbi-duration-moderate) var(--sbi-ease-smooth)" },
  { name: "--sbi-transition-fade", value: "opacity var(--sbi-duration-moderate) var(--sbi-ease-out)" },
  { name: "--sbi-transition-pop", value: "transform var(--sbi-duration-slower) var(--sbi-ease-spring-soft), opacity var(--sbi-duration-slower) var(--sbi-ease-spring-soft)" },
  { name: "--sbi-z-base", value: "0" },
  { name: "--sbi-z-chart", value: "2" },
  { name: "--sbi-z-dropdown", value: "20" },
  { name: "--sbi-z-overlay", value: "4" },
  { name: "--sbi-z-formula", value: "5" },
  { name: "--sbi-z-cursor", value: "100" },
  { name: "--sbi-z-loader", value: "10" },
  { name: "--sbi-z-nav", value: "1000" },
  { name: "--sbi-z-nav-dropdown", value: "1010" },
  { name: "--sbi-blur-nav", value: "12px" },
  { name: "--sbi-blur-dropdown", value: "16px" },
  { name: "--sbi-backdrop-saturate", value: "190%" },
  { name: "--sbi-backdrop-saturate-dropdown", value: "180%" },
  { name: "--sbi-surface-page", value: "hsl(var(--sbi-color-white))" },
  { name: "--sbi-surface-section-alt", value: "hsl(var(--sbi-color-warm-200))" },
  { name: "--sbi-surface-section-mesh", value: "hsl(var(--sbi-color-navy-50))" },
  { name: "--sbi-surface-card", value: "hsl(var(--sbi-color-white))" },
  { name: "--sbi-surface-card-elevated", value: "hsl(var(--sbi-color-white))" },
  { name: "--sbi-surface-card-dark", value: "hsl(var(--sbi-color-charcoal-900))" },
  { name: "--sbi-surface-canvas", value: "hsl(var(--sbi-color-warm-100))" },
  { name: "--sbi-surface-canvas-dashed", value: "hsl(var(--sbi-color-warm-100))" },
  { name: "--sbi-surface-input", value: "hsl(var(--sbi-color-slate-100))" },
  { name: "--sbi-surface-input-focus", value: "hsl(var(--sbi-color-white))" },
  { name: "--sbi-surface-nav", value: "hsl(var(--sbi-alpha-white-80))" },
  { name: "--sbi-surface-dropdown", value: "hsl(var(--sbi-alpha-white-90))" },
  { name: "--sbi-surface-console", value: "hsl(var(--sbi-color-slate-950))" },
  { name: "--sbi-surface-legacy-mockup", value: "hsl(var(--sbi-color-slate-100))" },
  { name: "--sbi-surface-inset", value: "hsl(var(--sbi-color-slate-50))" },
  { name: "--sbi-text-primary", value: "hsl(var(--sbi-color-charcoal-900))" },
  { name: "--sbi-text-secondary", value: "hsl(var(--sbi-color-charcoal-600))" },
  { name: "--sbi-text-tertiary", value: "hsl(var(--sbi-color-charcoal-500))" },
  { name: "--sbi-text-muted", value: "hsl(var(--sbi-color-charcoal-400))" },
  { name: "--sbi-text-inverse", value: "hsl(var(--sbi-color-charcoal-100))" },
  { name: "--sbi-text-on-dark", value: "hsl(var(--sbi-color-charcoal-100))" },
  { name: "--sbi-text-on-accent", value: "hsl(var(--sbi-color-white))" },
  { name: "--sbi-text-brand", value: "hsl(var(--sbi-color-blue-500))" },
  { name: "--sbi-text-brand-navy", value: "hsl(var(--sbi-color-navy-800))" },
  { name: "--sbi-text-accent", value: "hsl(var(--sbi-color-orange-500))" },
  { name: "--sbi-text-link", value: "hsl(var(--sbi-color-navy-600))" },
  { name: "--sbi-text-link-hover", value: "hsl(var(--sbi-color-blue-500))" },
  { name: "--sbi-text-success", value: "hsl(var(--sbi-color-green-brand))" },
  { name: "--sbi-text-danger", value: "hsl(var(--sbi-color-red-600))" },
  { name: "--sbi-text-console", value: "hsl(var(--sbi-color-slate-200))" },
  { name: "--sbi-text-console-dim", value: "hsl(var(--sbi-color-slate-400))" },
  { name: "--sbi-text-console-active", value: "hsl(var(--sbi-color-cyan-400))" },
  { name: "--sbi-text-console-error", value: "hsl(0 91% 71%)" },
  { name: "--sbi-border-default", value: "hsl(var(--sbi-color-charcoal-200))" },
  { name: "--sbi-border-subtle", value: "hsl(var(--sbi-color-warm-400))" },
  { name: "--sbi-border-muted", value: "hsl(var(--sbi-color-slate-200))" },
  { name: "--sbi-border-strong", value: "hsl(var(--sbi-color-slate-300))" },
  { name: "--sbi-border-focus", value: "hsl(var(--sbi-alpha-blue-40))" },
  { name: "--sbi-border-card", value: "hsl(var(--sbi-alpha-black-05))" },
  { name: "--sbi-border-dashed", value: "hsl(var(--sbi-alpha-black-08))" },
  { name: "--sbi-border-error", value: "hsl(var(--sbi-color-red-600))" },
  { name: "--sbi-border-console", value: "hsl(var(--sbi-color-slate-800))" },
  { name: "--sbi-action-primary-bg", value: "hsl(var(--sbi-color-orange-500))" },
  { name: "--sbi-action-primary-bg-hover", value: "hsl(var(--sbi-color-orange-600))" },
  { name: "--sbi-action-primary-bg-active", value: "hsl(var(--sbi-color-orange-700))" },
  { name: "--sbi-action-primary-text", value: "hsl(var(--sbi-color-white))" },
  { name: "--sbi-action-primary-shadow", value: "var(--sbi-shadow-glow-orange)" },
  { name: "--sbi-action-secondary-bg", value: "transparent" },
  { name: "--sbi-action-secondary-bg-hover", value: "hsl(var(--sbi-color-navy-50))" },
  { name: "--sbi-action-secondary-text", value: "hsl(var(--sbi-color-navy-800))" },
  { name: "--sbi-action-secondary-border", value: "hsl(var(--sbi-color-slate-300))" },
  { name: "--sbi-action-send-bg", value: "hsl(var(--sbi-color-green-brand))" },
  { name: "--sbi-action-send-bg-hover", value: "hsl(var(--sbi-color-green-800))" },
  { name: "--sbi-action-send-text", value: "hsl(var(--sbi-color-white))" },
  { name: "--sbi-action-ghost-bg-hover", value: "hsl(222 98% 66% / 0.08)" },
  { name: "--sbi-action-ghost-text", value: "hsl(var(--sbi-color-charcoal-500))" },
  { name: "--sbi-action-ghost-text-hover", value: "hsl(var(--sbi-color-blue-500))" },
  { name: "--sbi-focus-ring-color", value: "hsl(var(--sbi-color-orange-500))" },
  { name: "--sbi-focus-ring-width", value: "3px" },
  { name: "--sbi-focus-ring-offset", value: "2px" },
  { name: "--sbi-ai-user-bubble-bg", value: "hsl(var(--sbi-color-blue-500))" },
  { name: "--sbi-ai-user-bubble-text", value: "hsl(var(--sbi-color-white))" },
  { name: "--sbi-ai-system-bubble-bg", value: "hsl(var(--sbi-color-slate-200))" },
  { name: "--sbi-ai-system-bubble-text", value: "hsl(var(--sbi-color-slate-800))" },
  { name: "--sbi-ai-system-bubble-emphasis", value: "hsl(var(--sbi-color-slate-950))" },
  { name: "--sbi-ai-loader-color", value: "hsl(var(--sbi-color-blue-500))" },
  { name: "--sbi-ai-loader-track", value: "hsl(var(--sbi-alpha-blue-10))" },
  { name: "--sbi-ai-cursor-color", value: "hsl(var(--sbi-color-blue-500))" },
  { name: "--sbi-ai-sparkle-color", value: "hsl(var(--sbi-color-blue-500))" },
  { name: "--sbi-ai-input-bg", value: "hsl(var(--sbi-color-slate-100))" },
  { name: "--sbi-ai-input-bg-focus", value: "hsl(var(--sbi-color-white))" },
  { name: "--sbi-ai-input-placeholder", value: "hsl(var(--sbi-color-slate-400))" },
  { name: "--sbi-ai-chart-wrapper-bg", value: "hsl(var(--sbi-color-white))" },
  { name: "--sbi-ai-chart-wrapper-border", value: "hsl(var(--sbi-color-slate-200))" },
  { name: "--sbi-ai-thinking-text", value: "\"AI is thinking...\"" },
  { name: "--sbi-chart-axis", value: "hsl(var(--sbi-color-slate-300))" },
  { name: "--sbi-chart-gridline", value: "hsl(var(--sbi-color-slate-100))" },
  { name: "--sbi-chart-label", value: "hsl(var(--sbi-color-slate-400))" },
  { name: "--sbi-chart-title", value: "hsl(var(--sbi-color-slate-600))" },
  { name: "--sbi-chart-bar-primary", value: "hsl(var(--sbi-color-blue-500))" },
  { name: "--sbi-chart-bar-secondary", value: "hsl(var(--sbi-color-slate-400))" },
  { name: "--sbi-chart-line-primary", value: "hsl(var(--sbi-color-blue-500))" },
  { name: "--sbi-chart-target-line", value: "hsl(var(--sbi-color-red-600))" },
  { name: "--sbi-chart-gauge-track", value: "hsl(var(--sbi-color-slate-100))" },
  { name: "--sbi-chart-gauge-danger", value: "hsl(var(--sbi-color-red-600))" },
  { name: "--sbi-chart-gauge-success", value: "hsl(var(--sbi-color-green-brand))" },
  { name: "--sbi-chart-area-fill", value: "hsl(var(--sbi-alpha-blue-10))" },
  { name: "--sbi-kpi-on-track", value: "hsl(var(--sbi-color-green-500))" },
  { name: "--sbi-kpi-at-risk", value: "hsl(var(--sbi-color-amber-500))" },
  { name: "--sbi-kpi-off-track", value: "hsl(var(--sbi-color-red-600))" },
  { name: "--sbi-kpi-neutral", value: "hsl(var(--sbi-color-slate-400))" },
  { name: "--sbi-legacy-chrome-dark", value: "hsl(var(--sbi-color-slate-900))" },
  { name: "--sbi-legacy-chrome-mid", value: "hsl(var(--sbi-color-slate-700))" },
  { name: "--sbi-legacy-dimension", value: "hsl(199 89% 48%)" },
  { name: "--sbi-legacy-measure", value: "hsl(var(--sbi-color-green-400))" },
  { name: "--sbi-legacy-error", value: "hsl(var(--sbi-color-red-600))" },
  { name: "--sbi-legacy-error-bg", value: "hsl(var(--sbi-color-red-100))" },
  { name: "--sbi-legacy-progress", value: "hsl(var(--sbi-color-cyan-400))" },
  { name: "--sbi-nav-bg", value: "var(--sbi-surface-nav)" },
  { name: "--sbi-nav-blur", value: "var(--sbi-blur-nav)" },
  { name: "--sbi-nav-border", value: "var(--sbi-border-default)" },
  { name: "--sbi-nav-link-size", value: "var(--sbi-font-size-sm)" },
  { name: "--sbi-nav-link-color", value: "var(--sbi-action-ghost-text)" },
  { name: "--sbi-nav-link-color-active", value: "var(--sbi-text-primary)" },
  { name: "--sbi-nav-link-underline", value: "var(--sbi-text-primary)" },
  { name: "--sbi-nav-dropdown-highlight", value: "hsl(222 98% 66% / 1)" },
  { name: "--sbi-hero-tag-bg", value: "hsl(200 3% 36% / 0.05)" },
  { name: "--sbi-hero-tag-border", value: "hsl(200 3% 36% / 0.12)" },
  { name: "--sbi-hero-tag-text", value: "hsl(var(--sbi-color-charcoal-600))" },
  { name: "--sbi-hero-tag-radius", value: "var(--sbi-radius-full)" },
  { name: "--sbi-hero-accent", value: "var(--sbi-text-brand)" },
  { name: "--sbi-hero-cursor", value: "var(--sbi-ai-cursor-color)" },
  { name: "--sbi-hero-emoji-shadow", value: "var(--sbi-shadow-emoji)" },
  { name: "--sbi-discover-eyebrow-color", value: "var(--sbi-text-brand)" },
  { name: "--sbi-discover-title-color", value: "var(--sbi-text-primary)" },
  { name: "--sbi-discover-body-color", value: "var(--sbi-text-secondary)" },
  { name: "--sbi-goal-card-bg", value: "var(--sbi-surface-card-dark)" },
  { name: "--sbi-goal-card-radius", value: "var(--sbi-radius-2xl)" },
  { name: "--sbi-goal-card-padding", value: "var(--sbi-space-10)" },
  { name: "--sbi-goal-card-shadow", value: "var(--sbi-shadow-goal-dark)" },
  { name: "--sbi-goal-eyebrow-color", value: "var(--sbi-text-on-dark)" },
  { name: "--sbi-goal-title-color", value: "var(--sbi-text-on-dark)" },
  { name: "--sbi-goal-body-color", value: "var(--sbi-text-on-dark)" },
  { name: "--sbi-ai-card-bg", value: "var(--sbi-surface-card)" },
  { name: "--sbi-ai-card-radius", value: "var(--sbi-radius-2xl)" },
  { name: "--sbi-ai-card-padding", value: "var(--sbi-space-6)" },
  { name: "--sbi-ai-card-shadow", value: "var(--sbi-shadow-ai-card)" },
  { name: "--sbi-ai-card-border", value: "var(--sbi-border-card)" },
  { name: "--sbi-ai-viewport-bg", value: "var(--sbi-surface-canvas)" },
  { name: "--sbi-ai-viewport-border", value: "var(--sbi-border-dashed)" },
  { name: "--sbi-ai-viewport-radius", value: "var(--sbi-radius-xl)" },
  { name: "--sbi-ai-viewport-height", value: "250px" },
  { name: "--sbi-ai-input-radius", value: "var(--sbi-radius-full)" },
  { name: "--sbi-ai-input-padding-x", value: "var(--sbi-space-4)" },
  { name: "--sbi-ai-input-padding-y", value: "var(--sbi-space-1-5)" },
  { name: "--sbi-ai-send-size", value: "2.25rem" },
  { name: "--sbi-goal-section-bg", value: "var(--sbi-surface-section-alt)" },
  { name: "--sbi-goal-section-radius", value: "var(--sbi-radius-3xl)" },
  { name: "--sbi-goal-section-padding-y", value: "clamp(2.5rem, 6vw, 4.5rem)" },
  { name: "--sbi-button-radius", value: "var(--sbi-radius-xl)" },
  { name: "--sbi-button-radius-pill", value: "var(--sbi-radius-full)" },
  { name: "--sbi-button-padding-x", value: "var(--sbi-space-6)" },
  { name: "--sbi-button-padding-y", value: "var(--sbi-space-3)" },
  { name: "--sbi-button-font-size", value: "var(--sbi-font-size-md)" },
  { name: "--sbi-button-font-weight", value: "var(--sbi-font-weight-semibold)" },
  { name: "--sbi-process-border", value: "var(--sbi-border-subtle)" },
  { name: "--sbi-process-statement-size", value: "var(--sbi-font-size-xl)" },
  { name: "--sbi-process-label-color", value: "var(--sbi-text-tertiary)" },
  { name: "--sbi-footer-text", value: "var(--sbi-text-muted)" },
  { name: "--sbi-footer-divider", value: "var(--sbi-border-subtle)" },
  { name: "--sbi-bubble-radius", value: "var(--sbi-radius-xl)" },
  { name: "--sbi-bubble-radius-tail-user", value: "var(--sbi-radius-sm)" },
  { name: "--sbi-bubble-radius-tail-system", value: "var(--sbi-radius-sm)" },
  { name: "--sbi-bubble-padding-x", value: "var(--sbi-space-3)" },
  { name: "--sbi-bubble-padding-y", value: "var(--sbi-space-2)" },
  { name: "--sbi-bubble-font-size", value: "var(--sbi-font-size-sm)" },
  { name: "--sbi-bubble-max-width", value: "85%" },
  { name: "--sbi-mockup-radius", value: "var(--sbi-radius-lg)" },
  { name: "--sbi-mockup-shadow", value: "var(--sbi-shadow-mockup)" },
  { name: "--sbi-mockup-font-size", value: "var(--sbi-font-size-sm)" },
  { name: "--color-smartbi-blue", value: "hsl(var(--sbi-color-blue-500))" },
  { name: "--color-smartbi-navy", value: "hsl(var(--sbi-color-navy-800))" },
  { name: "--color-smartbi-orange", value: "hsl(var(--sbi-color-orange-500))" },
  { name: "--color-smartbi-charcoal", value: "hsl(var(--sbi-color-charcoal-900))" },
  { name: "--color-smartbi-green", value: "hsl(var(--sbi-color-green-brand))" }
];
